### ISSUE TITLE
Cheating

### ISSUE THREAD

**Issue by 00c** [HybridDog/replacer#1]
Player can mine and replace many stones at once with other than single node mode.
Could you please add option so players can use Only single node mode unless they have kick privileges.
Or disable node replacer below y -100.

**Comment by HybridDog** [comment]
How about enabling it if creative is enabled or the player has the give privilege?

**Comment by 00c** [comment]
That would be great .Only players with give privilege can use other than single node mode.

**Comment by HybridDog** [comment]
I've implemented it.

**Comment by 00c** [comment]
Great thanks

**Comment by 00c** [comment]
Somehow it does not work, player with or without give privs can't switch to any mode beside single
Even admin can't switch.
Looks as e ( speed ) button does not work, it does not switch mode but try to place

**Comment by HybridDog** [comment]
Thanks for testing, I accidentally used and instead of or and a not where there shouldn't be one there https://github.com/HybridDog/replacer/commit/e7e970cb01eb2c72e7da062719433602f3bf2614
