### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by 00c** [HybridDog/replacer#3]
Could you create a tool. Similar as node replace tool so you can switch between shovel axe pickaxe and sword.

**Comment by HybridDog** [comment]
What do you mean?

**Comment by 00c** [comment]
A mod. To replace shovel/pickaxe/sword/axe with 1 tool. Switch between them same way as node replacer. Shovel mode axe mode and so on. Multi tool.

**Comment by HybridDog** [comment]
It's possible: https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3491
One can also make a tool which has the digging capabilities of all mentioned tools at once (or better capabilities, e.g. the [superpick](https://github.com/HybridDog/superpick/blob/master/init.lua#L27)), why do you need a tool with those modes?

**Comment by 00c** [comment]
So you can have 1 tool ( takes 1 slot ) and can switch mode sword/shovel/axe/pickaxe. It could be very expensive to craft. I think its user friendly. When you have fast tool that can dig anything is not handy.

**Comment by HybridDog** [comment]
You could also make it possible to rotate tools in the inventory this way:
![swap](https://user-images.githubusercontent.com/3192173/34322513-23d17004-e829-11e7-8374-766eb3fb755a.png)
When pressing the key combination, tools are detected downwards and then rightwards until no tool can be found, then the tools are moved, the wielded one is put to the slot of the last one and you get the tool from the slot below.
This has the advantage that you can omit tools you don't need but it requires inventory space.

**Comment by 00c** [comment]
Could you please open issues in  https://github.com/HybridDog/farming_plus

**Comment by HybridDog** [comment]
Done.
#
Also, I've implemented tool rotation there: https://github.com/HybridDog/magic_sys/blob/master/toolrotate.lua

**Comment by 00c** [comment]
Great thanks!
