### ISSUE TITLE
Replacing slab trigger server crash

### ISSUE THREAD

**Issue by 00c** [HybridDog/replacer#6]
replacing  stairs:slab_wood with wood trigger server crash, does not happen with other slab

> : ACTION[Server]: Evil digs default:wood at (3332,9,-859)
> : ACTION[Server]: Evil places node default:wood at (3332,9,-859)
> : ACTION[Server]: Evil uses replacer:replacer, pointing at [node under=3333,9,-860 above=3333,10,-860]
> : ACTION[Server]: Evil digs stairs:slab_wood at (3333,9,-860)
> : [Server]: static int ModApiServer::l_get_player_ip(lua_State*): peer was not found
> : ACTION[Server]: JoeBlack leaves game. List of players: 
> : ACTION[Server]: Evil leaves game. List of players: 
> : ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'hbhunger' in callback item_OnUse(): .../bin/../builtin/common/misc_helpers.lua:717: attempt to perform arithmetic on field '?' (a nil value)
> : ERROR[Main]: stack traceback:
> : ERROR[Main]:       .../bin/../builtin/common/misc_helpers.lua:717: in function 'pointed_thing_to_face_pos'
> : ERROR[Main]:       .../bin/../games/Liberty Land/mods/stairs/init.lua:30: in function <../bin/../games/Liberty Land/mods/stairs/init.lua:20>
> : ERROR[Main]:       (tail call): ?
> : ERROR[Main]:       .../bin/../games/Liberty Land/mods/replacer/init.lua:410: in function 'replace_single_node'
> : ERROR[Main]:       .../bin/../games/Liberty Land/mods/replacer/init.lua:495: in function <.../bin/../games/Liberty Land/mods/replacer/init.lua:443>
> : ERROR[Main]:       (tail call): ?

**Comment by HybridDog** [comment]
I can't reproduce it in minetest_game.
